---
version: "2.4"
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PASSWORD=p@ssword
      - MARIADB_DATABASE=freepbx
      - MARIADB_USER=freepbx
    ports:
      - "3306:3306"
    networks:
      - freepbx

  freepbx:
    image: penguintech/freepbx
    build: .
    ports:
      - 8080:8080
      - 31000:31000
    networks:
      - freepbx
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  freepbx: