---
version: "2.4"
services:
  freepbx:
    image: penguintech/h-mdm
    build: .
    ports:
      - 8080:8080
      - 31000:31000
    networks:
      - freepbx
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  freepbx: