---
- name: Template odbc.ini config file
  template:
    src: templates/odbc_ini.j2
    dest: /etc/odbc.ini
    force: yes

- name: Template obc config file
  template:
    src: templates/odbcinst_ini.j2
    dest: /etc/odbcinst.ini
